# docker-compose.yaml
version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user         # 数据库用户名
      POSTGRES_PASSWORD: password # 数据库密码
      POSTGRES_DB: liveroomdb     # 数据库名
    ports:
      - "123:5432"             # 映射端口
    volumes:
      - postgres_data:/var/lib/postgresql/data # 数据卷持久化
    healthcheck:                  # 健康检查
      test: ["CMD-SHELL", "pg_isready -U user -d liveroomdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "124:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.9-alpine
    ports:
      - "125:4222"             # NATS 客户端端口
      # - "8222:8222"           # NATS 监控端口 (可选)

volumes:
  postgres_data:                # 定义数据卷