// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	EventID   pgtype.UUID        `json:"event_id"`
	SessionID pgtype.Text        `json:"session_id"`
	RoomID    pgtype.Text        `json:"room_id"`
	EventType string             `json:"event_type"`
	UserID    pgtype.Text        `json:"user_id"`
	EventTime pgtype.Timestamptz `json:"event_time"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
