// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Room struct {
	RoomID         string             `json:"room_id"`
	RoomName       string             `json:"room_name"`
	OwnerUserID    string             `json:"owner_user_id"`
	Status         string             `json:"status"`
	Platform       string             `json:"platform"`
	PlatformRoomID string             `json:"platform_room_id"`
	AreaName       pgtype.Text        `json:"area_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AnchorName     pgtype.Text        `json:"anchor_name"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}
