// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SessionMetricsTimeline struct {
	ID              int64              `json:"id"`
	SessionID       string             `json:"session_id"`
	Timestamp       pgtype.Timestamptz `json:"timestamp"`
	DanmakuCount    int64              `json:"danmaku_count"`
	GiftValue       int64              `json:"gift_value"`
	LikeCount       int64              `json:"like_count"`
	WatchedCount    int64              `json:"watched_count"`
	OnlineRankCount int64              `json:"online_rank_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
